### ISSUE TITLE
Please provide readme with usage isntructions

### ISSUE THREAD

**Issue by rafaeltcc** [daneden/kindle-highlights#24]
Hi, 

Could you provide a simple readme on how to use this software? Where do I need to copy My Clippings.txt? Should I use npm to use it?

Thanks

Rafael

**Comment by daneden** [comment]
Hey @rafaeltcc! You're probably looking for the repo that powers the sync to airtable: https://github.com/daneden/kindle-airtable-sync

This repo is just for displaying the highlights pulled from airtable!
